export const LOG_LIST_REQUEST = "LOG_LIST_REQUEST";
export const LOG_LIST_SUCCESS = "LOG_LIST_SUCCESS";
export const LOG_LIST_FAIL = "LOG_LIST_FAIL";

export const LOG_CREATE_REQUEST = "LOG_CREATE_REQUEST";
export const LOG_CREATE_SUCCESS = "LOG_CREATE_SUCCESS";
export const LOG_CREATE_FAIL = "LOG_CREATE_FAIL";

export const LOG_UPDATE_REQUEST = "LOG_UPDATE_REQUEST";
export const LOG_UPDATE_SUCCESS = "LOG_UPDATE_SUCCESS";
export const LOG_UPDATE_FAIL = "LOG_UPDATE_FAIL";

export const LOG_DELETE_REQUEST = "LOG_DELETE_REQUEST";
export const LOG_DELETE_SUCCESS = "LOG_DELETE_SUCCESS";
export const LOG_DELETE_FAIL = "LOG_DELETE_FAIL";
